#!/usr/bin/env bash
# Script that installs Nginx server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/school
sudo rm /var/www/school/index.nginx-debian.html
echo 'Hello world!' > /var/www/school/index.nginx-debian.html
sudo service nginx start
