#!/usr/bin/env bash
# Install the load balancer


apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
sed -i "$ a\listen 9888-lb-01\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\toption httpclose\n\toption forwardfor\n\tserver 9888-web-01 44.197.228.124:80 check\n\tserver 9888-web-02 3.236.248.179:80 check" /etc/haproxy/haproxy.cfg
service haproxy start
